package main

import (
	"github.com/amazon-translate/mcp-server/config"
	"github.com/amazon-translate/mcp-server/models"
	tools_x_amz_target_awsshinefrontendservice_20170701_createparalleldata "github.com/amazon-translate/mcp-server/tools/x_amz_target_awsshinefrontendservice_20170701_createparalleldata"
	tools_x_amz_target_awsshinefrontendservice_20170701_describetexttranslationjob "github.com/amazon-translate/mcp-server/tools/x_amz_target_awsshinefrontendservice_20170701_describetexttranslationjob"
	tools_x_amz_target_awsshinefrontendservice_20170701_importterminology "github.com/amazon-translate/mcp-server/tools/x_amz_target_awsshinefrontendservice_20170701_importterminology"
	tools_x_amz_target_awsshinefrontendservice_20170701_translatedocument "github.com/amazon-translate/mcp-server/tools/x_amz_target_awsshinefrontendservice_20170701_translatedocument"
	tools_x_amz_target_awsshinefrontendservice_20170701_listtagsforresource "github.com/amazon-translate/mcp-server/tools/x_amz_target_awsshinefrontendservice_20170701_listtagsforresource"
	tools_x_amz_target_awsshinefrontendservice_20170701_tagresource "github.com/amazon-translate/mcp-server/tools/x_amz_target_awsshinefrontendservice_20170701_tagresource"
	tools_x_amz_target_awsshinefrontendservice_20170701_updateparalleldata "github.com/amazon-translate/mcp-server/tools/x_amz_target_awsshinefrontendservice_20170701_updateparalleldata"
	tools_x_amz_target_awsshinefrontendservice_20170701_listlanguages "github.com/amazon-translate/mcp-server/tools/x_amz_target_awsshinefrontendservice_20170701_listlanguages"
	tools_x_amz_target_awsshinefrontendservice_20170701_starttexttranslationjob "github.com/amazon-translate/mcp-server/tools/x_amz_target_awsshinefrontendservice_20170701_starttexttranslationjob"
	tools_x_amz_target_awsshinefrontendservice_20170701_listparalleldata "github.com/amazon-translate/mcp-server/tools/x_amz_target_awsshinefrontendservice_20170701_listparalleldata"
	tools_x_amz_target_awsshinefrontendservice_20170701_listterminologies "github.com/amazon-translate/mcp-server/tools/x_amz_target_awsshinefrontendservice_20170701_listterminologies"
	tools_x_amz_target_awsshinefrontendservice_20170701_getparalleldata "github.com/amazon-translate/mcp-server/tools/x_amz_target_awsshinefrontendservice_20170701_getparalleldata"
	tools_x_amz_target_awsshinefrontendservice_20170701_deleteparalleldata "github.com/amazon-translate/mcp-server/tools/x_amz_target_awsshinefrontendservice_20170701_deleteparalleldata"
	tools_x_amz_target_awsshinefrontendservice_20170701_translatetext "github.com/amazon-translate/mcp-server/tools/x_amz_target_awsshinefrontendservice_20170701_translatetext"
	tools_x_amz_target_awsshinefrontendservice_20170701_deleteterminology "github.com/amazon-translate/mcp-server/tools/x_amz_target_awsshinefrontendservice_20170701_deleteterminology"
	tools_x_amz_target_awsshinefrontendservice_20170701_listtexttranslationjobs "github.com/amazon-translate/mcp-server/tools/x_amz_target_awsshinefrontendservice_20170701_listtexttranslationjobs"
	tools_x_amz_target_awsshinefrontendservice_20170701_stoptexttranslationjob "github.com/amazon-translate/mcp-server/tools/x_amz_target_awsshinefrontendservice_20170701_stoptexttranslationjob"
	tools_x_amz_target_awsshinefrontendservice_20170701_untagresource "github.com/amazon-translate/mcp-server/tools/x_amz_target_awsshinefrontendservice_20170701_untagresource"
	tools_x_amz_target_awsshinefrontendservice_20170701_getterminology "github.com/amazon-translate/mcp-server/tools/x_amz_target_awsshinefrontendservice_20170701_getterminology"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_x_amz_target_awsshinefrontendservice_20170701_createparalleldata.CreateCreateparalleldataTool(cfg),
		tools_x_amz_target_awsshinefrontendservice_20170701_describetexttranslationjob.CreateDescribetexttranslationjobTool(cfg),
		tools_x_amz_target_awsshinefrontendservice_20170701_importterminology.CreateImportterminologyTool(cfg),
		tools_x_amz_target_awsshinefrontendservice_20170701_translatedocument.CreateTranslatedocumentTool(cfg),
		tools_x_amz_target_awsshinefrontendservice_20170701_listtagsforresource.CreateListtagsforresourceTool(cfg),
		tools_x_amz_target_awsshinefrontendservice_20170701_tagresource.CreateTagresourceTool(cfg),
		tools_x_amz_target_awsshinefrontendservice_20170701_updateparalleldata.CreateUpdateparalleldataTool(cfg),
		tools_x_amz_target_awsshinefrontendservice_20170701_listlanguages.CreateListlanguagesTool(cfg),
		tools_x_amz_target_awsshinefrontendservice_20170701_starttexttranslationjob.CreateStarttexttranslationjobTool(cfg),
		tools_x_amz_target_awsshinefrontendservice_20170701_listparalleldata.CreateListparalleldataTool(cfg),
		tools_x_amz_target_awsshinefrontendservice_20170701_listterminologies.CreateListterminologiesTool(cfg),
		tools_x_amz_target_awsshinefrontendservice_20170701_getparalleldata.CreateGetparalleldataTool(cfg),
		tools_x_amz_target_awsshinefrontendservice_20170701_deleteparalleldata.CreateDeleteparalleldataTool(cfg),
		tools_x_amz_target_awsshinefrontendservice_20170701_translatetext.CreateTranslatetextTool(cfg),
		tools_x_amz_target_awsshinefrontendservice_20170701_deleteterminology.CreateDeleteterminologyTool(cfg),
		tools_x_amz_target_awsshinefrontendservice_20170701_listtexttranslationjobs.CreateListtexttranslationjobsTool(cfg),
		tools_x_amz_target_awsshinefrontendservice_20170701_stoptexttranslationjob.CreateStoptexttranslationjobTool(cfg),
		tools_x_amz_target_awsshinefrontendservice_20170701_untagresource.CreateUntagresourceTool(cfg),
		tools_x_amz_target_awsshinefrontendservice_20170701_getterminology.CreateGetterminologyTool(cfg),
	}
}
